# Generated by Django 4.2.6 on 2023-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="degree",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="elevation_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="exaultation_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="iniciation_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="installation_date",
            field=models.DateField(),
        ),
    ]
