# Generated by Django 4.2.6 on 2023-12-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_post_date_alter_profile_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="elevation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="exaultation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="installation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
